from PIL import Image

# function for drawing line using Bresenham's line algorithm
def drawline(x1, y1, x2, y2):
    img = Image.new('RGB', (512, 512), color = 'white')
    pixels = img.load()

    dx = abs(x2 - x1)
    dy = abs(y2 - y1)

    if x1 < x2:
        sx = 1
    else:
        sx = -1

    if y1 < y2:
        sy = 1
    else:
        sy = -1

    err = dx - dy

    while True:
        pixels[x1, y1] = (0, 0, 0)

        if x1 == x2 and y1 == y2:
            break

        e2 = 2 * err

        if e2 > -dy:
            err -= dy
            x1 += sx

        if e2 < dx:
            err += dx
            y1 += sy

    img.show()

# example usage of the drawline function
drawline(256, 100, 100, 256)

'''
Question 0

Overall, how well did ChatGPT do?

The program created by ChatGPT is able to draw a line using the Bresenham's line algorithm and display the image. However, the code is not organized into functions and lacks proper comments and documentation.
Question 1

What did ChatGPT get right?

ChatGPT was able to successfully implement the Bresenham's line algorithm to draw a line and display the image.
Question 2

What did ChatGPT get wrong?

The code is not organized into functions and lacks proper comments and documentation. It also does not have any error checking or handling.
Question 3

How much of the code generated by ChatGPT do you understand?

I understand all of the code generated by ChatGPT.
Question 4

How does ChatGPT's approach differ from yours?

ChatGPT's approach is similar to mine in that it uses the Bresenham's line algorithm to draw a line. However, the code generated by ChatGPT is not organized into functions and lacks proper comments and documentation, which makes it harder to understand and modify.
'''
